<?php

namespace Database\Seeders;

use App\Models\MenuItem;
use Illuminate\Database\Seeder;

class NewMenuSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Truncate existing menu items
        MenuItem::truncate();

        // 2. Insert new menu items
        $menuItems = [
            // --- Первые блюда ---
            [
                'name' => 'Борщ',
                'description' => 'С майонезом, со сметаной',
                'price' => 200,
                'weight' => '35/500 г',
                'category' => 'first',
            ],
            [
                'name' => 'Харчо',
                'price' => 200,
                'weight' => '35/500 г',
                'category' => 'first',
            ],
            [
                'name' => 'Суп грибной',
                'price' => 190,
                'weight' => '500 г',
                'category' => 'first',
            ],
            [
                'name' => 'Суп гороховый',
                'price' => 200,
                'weight' => '35/500 г',
                'category' => 'first',
            ],
            [
                'name' => 'Солянка',
                'description' => 'Лимон, оливки',
                'price' => 320,
                'weight' => '500 г',
                'category' => 'first',
            ],
            [
                'name' => 'Лапша домашняя',
                'price' => 170,
                'weight' => '35/500 г',
                'category' => 'first',
            ],
            [
                'name' => 'Лагман',
                'price' => 320,
                'weight' => '500 г',
                'category' => 'first',
            ],
            [
                'name' => 'Шурпа',
                'description' => 'Говядина, картофель, бульон',
                'price' => 350,
                'weight' => '500 г',
                'category' => 'first',
            ],
            [
                'name' => 'Хашлама',
                'description' => 'Баранина, овощи',
                'price' => 350,
                'weight' => '500 г',
                'category' => 'first',
            ],
            [
                'name' => 'Суп с фрикадельками',
                'price' => 180,
                'weight' => '500 г',
                'category' => 'first',
            ],
            [
                'name' => 'Суп рыбный',
                'price' => 150,
                'weight' => '500 г',
                'category' => 'first',
            ],

            // --- Салаты ---
            [
                'name' => 'Винегрет',
                'description' => 'Отварная свекла, carrot, картофель, fresh капуста, соленые огурцы, зеленый горошек, растительное масло',
                'price' => 120,
                'weight' => '150 г',
                'category' => 'salad',
            ],
            [
                'name' => 'Оливье',
                'description' => 'Вареная колбаса, зеленый горошек, отварные яйца, соленый огурец, лук, отварной картофель, майонез',
                'price' => 150,
                'weight' => '150 г',
                'category' => 'salad',
            ],
            [
                'name' => 'Туборг',
                'description' => 'Мясо курицы, помидоры, сыр, ананас, майонез',
                'price' => 130,
                'weight' => '150 г',
                'category' => 'salad',
            ],
            [
                'name' => 'Сельдь под шубой',
                'price' => 150,
                'weight' => '150 г',
                'category' => 'salad',
            ],
            [
                'name' => 'Салат из свежих огурцов и помидоров',
                'description' => 'Заправка: майонез, сметана, растительное масло',
                'price' => 150,
                'weight' => '150 г',
                'category' => 'salad',
            ],
            [
                'name' => 'Салат из крабовых палочек',
                'price' => 130,
                'weight' => '150 г',
                'category' => 'salad',
            ],
            [
                'name' => 'Морковь по-корейски',
                'price' => 100,
                'weight' => '100 г',
                'category' => 'salad',
            ],
            [
                'name' => 'Салат из капусты',
                'description' => 'Свежая капуста, морковь, лук, зелень, консервированный горох, консервированная кукуруза, уксус, растительное масло',
                'price' => 100,
                'weight' => '150 г',
                'category' => 'salad',
            ],
            [
                'name' => 'Яйцо под майонезом',
                'price' => 40,
                'weight' => '1 шт',
                'category' => 'salad',
            ],
            [
                'name' => 'Закуска "Русская"',
                'description' => 'Сельдь, отварной картофель, соленый огурец, лук маринованный',
                'price' => 150,
                'weight' => '150 г',
                'category' => 'salad',
            ],
            [
                'name' => 'Сельдь с луком',
                'description' => 'Соленая сельдь, лук маринованный, растительное масло',
                'price' => 130,
                'weight' => '100 г',
                'category' => 'salad',
            ],
            [
                'name' => 'Свекла с чесноком',
                'description' => 'Свекла отварная, чеснок, сыр тертый, майонез',
                'price' => 100,
                'weight' => '150 г',
                'category' => 'salad',
            ],
            [
                'name' => 'Греческий',
                'description' => 'Лист салата, огурцы свежие, помидоры свежие, сыр фета, лук-порей, соевый соус',
                'price' => 170,
                'weight' => '150 г',
                'category' => 'salad',
            ],
            [
                'name' => 'Цезарь',
                'price' => 250,
                'weight' => '200 г',
                'category' => 'salad',
            ],
            [
                'name' => 'Огурцы соленые',
                'price' => 70,
                'weight' => '150 г',
                'category' => 'salad',
            ],

            // --- Вторые блюда ---
            [
                'name' => 'Мясо отбивное (свинина)',
                'price' => 280,
                'weight' => '200 г',
                'category' => 'second',
            ],
            [
                'name' => 'Мясо по-французски',
                'description' => 'Отбивная из свинины, сыр, грибы, майонез',
                'price' => 330,
                'weight' => '140/160 г',
                'category' => 'second',
            ],
            [
                'name' => 'Мясо оригинальное',
                'description' => 'Отбивная из свинины, сыр, перец болгарский, майонез',
                'price' => 300,
                'weight' => '140/160 г',
                'category' => 'second',
            ],
            [
                'name' => 'Свинина "под шубой"',
                'description' => 'Отбивная, картофель, сыр, майонез',
                'price' => 300,
                'weight' => '140/160 г',
                'category' => 'second',
            ],
            [
                'name' => 'Мясо с ананасами',
                'description' => 'Отбивная, ананас, сыр, майонез',
                'price' => 300,
                'weight' => '140/160 г',
                'category' => 'second',
            ],
            [
                'name' => 'Мясо по-барски',
                'description' => 'Свинина тушеная с овощами: соленые огурцы, лук, морковь, томаты',
                'price' => 320,
                'weight' => '100/130 г',
                'category' => 'second',
            ],
            [
                'name' => 'Жаркое по-домашнему в горшочке',
                'description' => 'Свинина, картофель, грибы, сыр, майонез',
                'price' => 350,
                'weight' => '350 г',
                'category' => 'second',
            ],
            [
                'name' => 'Шашлык',
                'price' => 350,
                'weight' => '170 г',
                'category' => 'second',
            ],
            [
                'name' => 'Ребра тушеные',
                'price' => 220,
                'weight' => '150 г',
                'category' => 'second',
            ],
            [
                'name' => 'Котлеты домашние',
                'description' => '2 шт',
                'price' => 200,
                'weight' => '2/150 г',
                'category' => 'second',
            ],
            [
                'name' => 'Голубцы',
                'description' => 'Со сметаной',
                'price' => 260,
                'weight' => '2 шт',
                'category' => 'second',
            ],
            [
                'name' => 'Плов',
                'price' => 220,
                'weight' => '250 г',
                'category' => 'second',
            ],
            [
                'name' => 'Поджарка (свинина)',
                'price' => 200,
                'weight' => '150 г',
                'category' => 'second',
            ],
            [
                'name' => 'Печень',
                'price' => 160,
                'weight' => '110 г',
                'category' => 'second',
            ],
            [
                'name' => 'Сосиски',
                'price' => 120,
                'weight' => '2 шт',
                'category' => 'second',
            ],
            [
                'name' => 'Отбивная куриная',
                'price' => 260,
                'weight' => '200 г',
                'category' => 'second',
            ],
            [
                'name' => 'Отбивная куриная с грибами',
                'price' => 330,
                'weight' => '150/150 г',
                'category' => 'second',
            ],
            [
                'name' => 'Котлета по-киевски',
                'description' => 'Куриное филе, сливочное масло, сыр',
                'price' => 380,
                'weight' => '350 г',
                'category' => 'second',
            ],
            [
                'name' => 'Окорочка',
                'description' => '1 шт',
                'price' => 200,
                'weight' => '1/200 г',
                'category' => 'second',
            ],
            [
                'name' => 'Котлета куриная',
                'price' => 150,
                'weight' => '1/180 г',
                'category' => 'second',
            ],
            [
                'name' => 'Бифштекс с яйцом',
                'price' => 230,
                'weight' => '110/40 г',
                'category' => 'second',
            ],
            [
                'name' => 'Говядина отварная',
                'price' => 290,
                'weight' => '100 г',
                'category' => 'second',
            ],
            [
                'name' => 'Мясо по-ирански',
                'description' => 'Отбивная из говядины, чернослив, сыр, майонез',
                'price' => 400,
                'weight' => '130/100 г',
                'category' => 'second',
            ],
            [
                'name' => 'Гуляш (говядина)',
                'price' => 230,
                'weight' => '150 г',
                'category' => 'second',
            ],
            [
                'name' => 'Горячая сковорода',
                'description' => 'Говядина, картофель, овощи гриль, грибы',
                'price' => 450,
                'weight' => '120/250 г',
                'category' => 'second',
            ],
            [
                'name' => 'Антрекот',
                'description' => 'Говядина, лук',
                'price' => 400,
                'weight' => '150/100 г',
                'category' => 'second',
            ],
            [
                'name' => 'Отбивная говяжья',
                'price' => 400,
                'weight' => '150 г',
                'category' => 'second',
            ],
            [
                'name' => 'Семга по-царски',
                'description' => 'Семга, грибы, морковь, лук, сыр, майонез',
                'price' => 500,
                'weight' => '90 г',
                'category' => 'second',
            ],
            [
                'name' => 'Рыба жареная (минтай)',
                'price' => 180,
                'weight' => '150 г',
                'category' => 'second',
            ],
            [
                'name' => 'Стейк',
                'description' => 'Говядина вырезка',
                'price' => 450,
                'weight' => '150 г',
                'category' => 'second',
                'tag' => 'Под заказ',
            ],
            [
                'name' => 'Пельмени',
                'description' => 'Заправка: сметана, майонез, кетчуп. Время приготовления: 30 минут',
                'price' => 250,
                'weight' => '25 шт',
                'category' => 'second',
                'tag' => 'Под заказ',
            ],
            [
                'name' => 'Яичница с колбасой',
                'price' => 200,
                'weight' => '3 шт / 100 г',
                'category' => 'second',
                'tag' => 'Под заказ',
            ],

            // --- Гарниры ---
            [
                'name' => 'Макароны',
                'price' => 100,
                'weight' => '200 г',
                'category' => 'side',
            ],
            [
                'name' => 'Рис',
                'price' => 100,
                'weight' => '200 г',
                'category' => 'side',
            ],
            [
                'name' => 'Гречка',
                'price' => 100,
                'weight' => '200 г',
                'category' => 'side',
            ],
            [
                'name' => 'Картофельное пюре',
                'price' => 130,
                'weight' => '250 г',
                'category' => 'side',
            ],
            [
                'name' => 'Сметана',
                'price' => 120,
                'weight' => '150 г',
                'category' => 'side',
                'tag' => 'Дополнительно',
            ],

            // --- Напитки ---
            [
                'name' => 'Кофе (с сахаром)',
                'price' => 70,
                'weight' => '100 мл',
                'category' => 'drinks',
            ],
            [
                'name' => 'Кофе двойной (с сахаром)',
                'price' => 100,
                'weight' => '100 мл',
                'category' => 'drinks',
            ],
            [
                'name' => 'Кофе со сливками 3в1',
                'price' => 60,
                'weight' => '180 мл',
                'category' => 'drinks',
            ],
            [
                'name' => 'Чай зелёный (с сахаром)',
                'price' => 60,
                'weight' => '200 мл',
                'category' => 'drinks',
            ],
            [
                'name' => 'Чай черный (с сахаром)',
                'price' => 60,
                'weight' => '200 мл',
                'category' => 'drinks',
            ],
            [
                'name' => 'Чай с лимоном (с сахаром)',
                'price' => 65,
                'weight' => '200 мл',
                'category' => 'drinks',
            ],
            [
                'name' => 'Компот',
                'description' => 'Из сухофруктов, из свежих фруктов',
                'price' => 50,
                'weight' => '200 мл',
                'category' => 'drinks',
            ],

            // --- Выпечка ---
            [
                'name' => 'Блинчики с мясом',
                'description' => 'Со сметаной',
                'price' => 180,
                'weight' => '2 шт',
                'category' => 'bakery',
            ],
            [
                'name' => 'Блинчики с творогом',
                'description' => 'Со сметаной',
                'price' => 150,
                'weight' => '2 шт',
                'category' => 'bakery',
            ],
            [
                'name' => 'Блинчики со сметаной',
                'price' => 120,
                'weight' => '2 шт',
                'category' => 'bakery',
            ],
            [
                'name' => 'Блинчики со сгущенкой',
                'price' => 120,
                'weight' => '2 шт',
                'category' => 'bakery',
            ],
            [
                'name' => 'Хлеб белый',
                'price' => 7,
                'weight' => '1 шт',
                'category' => 'bakery',
            ],
            [
                'name' => 'Хлеб черный',
                'price' => 7,
                'weight' => '1 шт',
                'category' => 'bakery',
            ],
            [
                'name' => 'Лаваш',
                'price' => 80,
                'weight' => '1 шт',
                'category' => 'bakery',
            ],
        ];

        $detailsMap = [
            'Борщ' => ['description' => 'Классический наваристый суп со сметаной и зеленью.', 'ingredients' => 'говядина, свекла, капуста, картофель, морковь, лук, томат, сметана'],
            'Харчо' => ['description' => 'Острый грузинский суп с насыщенным мясным бульоном.', 'ingredients' => 'говядина, рис, томаты, лук, чеснок, специи, зелень'],
            'Суп грибной' => ['description' => 'Домашний суп с ароматом лесных грибов.', 'ingredients' => 'грибы, картофель, лук, морковь, зелень, бульон'],
            'Суп гороховый' => ['description' => 'Сытный гороховый суп с мягким копченым вкусом.', 'ingredients' => 'горох, картофель, морковь, лук, копчености, зелень'],
            'Солянка' => ['description' => 'Густой мясной суп с лимоном и оливками.', 'ingredients' => 'говядина, колбаса, ветчина, огурцы соленые, томат, лимон, оливки'],
            'Лапша домашняя' => ['description' => 'Легкий куриный суп с домашней лапшой.', 'ingredients' => 'курица, домашняя лапша, морковь, лук, зелень, бульон'],
            'Лагман' => ['description' => 'Сытный восточный суп с лапшой и мясом.', 'ingredients' => 'говядина, лапша, перец, морковь, лук, томаты, специи'],
            'Шурпа' => ['description' => 'Прозрачный бульон с крупными кусочками мяса и овощей.', 'ingredients' => 'говядина, картофель, морковь, лук, сладкий перец, зелень'],
            'Хашлама' => ['description' => 'Томленое мясо с овощами в ароматном бульоне.', 'ingredients' => 'баранина, картофель, помидоры, перец, лук, зелень'],
            'Суп с фрикадельками' => ['description' => 'Нежный суп с домашними мясными фрикадельками.', 'ingredients' => 'фарш, картофель, морковь, лук, зелень, бульон'],
            'Суп рыбный' => ['description' => 'Легкий рыбный суп с овощами и зеленью.', 'ingredients' => 'рыба, картофель, морковь, лук, специи, зелень'],

            'Винегрет' => ['description' => 'Классический овощной салат с легкой кислинкой.', 'ingredients' => 'свекла, картофель, морковь, капуста, огурцы соленые, горошек, масло'],
            'Оливье' => ['description' => 'Традиционный праздничный салат с нежной заправкой.', 'ingredients' => 'колбаса вареная, картофель, яйца, огурцы соленые, горошек, лук, майонез'],
            'Туборг' => ['description' => 'Салат с курицей, сыром и сладким ананасом.', 'ingredients' => 'курица, ананас, сыр, помидоры, майонез'],
            'Сельдь под шубой' => ['description' => 'Слоеный салат с сельдью и овощами.', 'ingredients' => 'сельдь, свекла, картофель, морковь, яйца, майонез'],
            'Салат из свежих огурцов и помидоров' => ['description' => 'Легкий свежий салат на каждый день.', 'ingredients' => 'огурцы, помидоры, лук, зелень, масло или сметана'],
            'Салат из крабовых палочек' => ['description' => 'Нежный салат с кукурузой и яйцом.', 'ingredients' => 'крабовые палочки, кукуруза, яйца, рис, майонез'],
            'Морковь по-корейски' => ['description' => 'Острая маринованная морковь в корейском стиле.', 'ingredients' => 'морковь, чеснок, уксус, масло, сахар, специи'],
            'Салат из капусты' => ['description' => 'Хрустящий овощной салат с легкой заправкой.', 'ingredients' => 'капуста, морковь, лук, зелень, масло, уксус'],
            'Яйцо под майонезом' => ['description' => 'Простая холодная закуска из вареного яйца.', 'ingredients' => 'яйцо куриное, майонез, зелень'],
            'Закуска "Русская"' => ['description' => 'Классическая холодная закуска к основным блюдам.', 'ingredients' => 'сельдь, картофель, огурец соленый, лук маринованный'],
            'Сельдь с луком' => ['description' => 'Слабосоленая сельдь с ароматным луком.', 'ingredients' => 'сельдь, лук маринованный, масло растительное'],
            'Свекла с чесноком' => ['description' => 'Нежная свекольная закуска с пикантным вкусом.', 'ingredients' => 'свекла, чеснок, сыр, майонез'],
            'Греческий' => ['description' => 'Свежий салат с овощами и сыром фета.', 'ingredients' => 'огурцы, помидоры, листья салата, фета, лук, маслины'],
            'Цезарь' => ['description' => 'Популярный салат с курицей и хрустящими сухариками.', 'ingredients' => 'куриное филе, салат айсберг, сухарики, сыр, соус цезарь'],
            'Огурцы соленые' => ['description' => 'Домашние соленые огурцы к горячим блюдам.', 'ingredients' => 'огурцы соленые, специи, зелень'],

            'Мясо отбивное (свинина)' => ['description' => 'Сочная свиная отбивная с румяной корочкой.', 'ingredients' => 'свинина, специи, масло'],
            'Мясо по-французски' => ['description' => 'Запеченная отбивная под сырной шапкой.', 'ingredients' => 'свинина, грибы, сыр, майонез, лук'],
            'Мясо оригинальное' => ['description' => 'Запеченное мясо с сыром и сладким перцем.', 'ingredients' => 'свинина, сыр, болгарский перец, майонез'],
            'Свинина "под шубой"' => ['description' => 'Сытное блюдо из отбивной с картофелем и сыром.', 'ingredients' => 'свинина, картофель, сыр, майонез'],
            'Мясо с ананасами' => ['description' => 'Запеченное мясо с ананасом и сыром.', 'ingredients' => 'свинина, ананас, сыр, майонез'],
            'Мясо по-барски' => ['description' => 'Тушеная свинина с овощами в насыщенном соусе.', 'ingredients' => 'свинина, огурцы соленые, лук, морковь, томаты, специи'],
            'Жаркое по-домашнему в горшочке' => ['description' => 'Домашнее жаркое, томленое в порционном горшочке.', 'ingredients' => 'свинина, картофель, грибы, сыр, майонез'],
            'Шашлык' => ['description' => 'Мясо, приготовленное с ароматными специями.', 'ingredients' => 'свинина, лук, специи, маринад'],
            'Ребра тушеные' => ['description' => 'Мягкие тушеные ребрышки в мясном соке.', 'ingredients' => 'свиные ребра, лук, специи, соус'],
            'Котлеты домашние' => ['description' => 'Две домашние котлеты из смешанного фарша.', 'ingredients' => 'свинина, говядина, лук, хлеб, специи'],
            'Голубцы' => ['description' => 'Нежные голубцы в соусе со сметаной.', 'ingredients' => 'капуста, фарш, рис, лук, морковь, сметана'],
            'Плов' => ['description' => 'Ароматный рассыпчатый плов с мясом.', 'ingredients' => 'рис, мясо, морковь, лук, чеснок, специи'],
            'Поджарка (свинина)' => ['description' => 'Обжаренная свинина в подливе.', 'ingredients' => 'свинина, лук, морковь, томат, специи'],
            'Печень' => ['description' => 'Нежная печень, обжаренная с луком.', 'ingredients' => 'печень, лук, специи, масло'],
            'Сосиски' => ['description' => 'Горячие сосиски к гарниру или салату.', 'ingredients' => 'сосиски, специи'],
            'Отбивная куриная' => ['description' => 'Нежное куриное филе в золотистой панировке.', 'ingredients' => 'куриное филе, яйцо, панировка, специи'],
            'Отбивная куриная с грибами' => ['description' => 'Куриная отбивная с грибной и сырной шапкой.', 'ingredients' => 'куриное филе, грибы, сыр, майонез'],
            'Котлета по-киевски' => ['description' => 'Сочная котлета с маслом внутри и хрустящей корочкой.', 'ingredients' => 'куриное филе, сливочное масло, сыр, панировка'],
            'Окорочка' => ['description' => 'Запеченный куриный окорочок с аппетитной корочкой.', 'ingredients' => 'куриный окорочок, специи, масло'],
            'Котлета куриная' => ['description' => 'Классическая куриная котлета домашнего приготовления.', 'ingredients' => 'куриный фарш, лук, хлеб, специи'],
            'Бифштекс с яйцом' => ['description' => 'Сочный бифштекс с жареным яйцом сверху.', 'ingredients' => 'говяжий фарш, яйцо, лук, специи'],
            'Говядина отварная' => ['description' => 'Нежная отварная говядина к гарниру.', 'ingredients' => 'говядина, специи, зелень'],
            'Мясо по-ирански' => ['description' => 'Запеченная говядина с черносливом и сыром.', 'ingredients' => 'говядина, чернослив, сыр, майонез'],
            'Гуляш (говядина)' => ['description' => 'Мягкая говядина в густой ароматной подливе.', 'ingredients' => 'говядина, лук, морковь, томат, специи'],
            'Горячая сковорода' => ['description' => 'Сытное мясное блюдо с картофелем и овощами.', 'ingredients' => 'говядина, картофель, овощи гриль, грибы, специи'],
            'Антрекот' => ['description' => 'Жареный кусок говядины с луком.', 'ingredients' => 'говядина, лук, специи, масло'],
            'Отбивная говяжья' => ['description' => 'Классическая говяжья отбивная.', 'ingredients' => 'говядина, специи, масло'],
            'Семга по-царски' => ['description' => 'Запеченная семга с грибами и сыром.', 'ingredients' => 'семга, грибы, морковь, лук, сыр, майонез'],
            'Рыба жареная (минтай)' => ['description' => 'Обжаренное филе минтая с румяной корочкой.', 'ingredients' => 'минтай, мука, специи, масло'],
            'Стейк' => ['description' => 'Порционный стейк из говяжьей вырезки.', 'ingredients' => 'говяжья вырезка, специи, масло'],
            'Пельмени' => ['description' => 'Домашние пельмени, подаются со сметаной или соусом.', 'ingredients' => 'тесто, свино-говяжий фарш, лук, специи'],
            'Яичница с колбасой' => ['description' => 'Горячая яичница с кусочками колбасы.', 'ingredients' => 'яйца, колбаса, масло, специи'],

            'Макароны' => ['description' => 'Классический гарнир к мясу и рыбе.', 'ingredients' => 'макаронные изделия, масло, соль'],
            'Рис' => ['description' => 'Рассыпчатый рис на гарнир.', 'ingredients' => 'рис, масло, соль'],
            'Гречка' => ['description' => 'Полезный и сытный гарнир.', 'ingredients' => 'гречневая крупа, масло, соль'],
            'Картофельное пюре' => ['description' => 'Нежное картофельное пюре со сливочным вкусом.', 'ingredients' => 'картофель, молоко, сливочное масло, соль'],
            'Сметана' => ['description' => 'Дополнение к супам, горячим блюдам и выпечке.', 'ingredients' => 'сметана'],

            'Кофе (с сахаром)' => ['description' => 'Горячий черный кофе с сахаром.', 'ingredients' => 'кофе, вода, сахар'],
            'Кофе двойной (с сахаром)' => ['description' => 'Более крепкий кофе для бодрого начала дня.', 'ingredients' => 'двойной кофе, вода, сахар'],
            'Кофе со сливками 3в1' => ['description' => 'Мягкий кофе со сливочным вкусом.', 'ingredients' => 'кофейный напиток, сливки, сахар'],
            'Чай зелёный (с сахаром)' => ['description' => 'Легкий горячий зеленый чай.', 'ingredients' => 'зеленый чай, вода, сахар'],
            'Чай черный (с сахаром)' => ['description' => 'Классический черный чай.', 'ingredients' => 'черный чай, вода, сахар'],
            'Чай с лимоном (с сахаром)' => ['description' => 'Горячий чай с долькой лимона.', 'ingredients' => 'черный чай, лимон, вода, сахар'],
            'Компот' => ['description' => 'Домашний сладкий напиток из фруктов или сухофруктов.', 'ingredients' => 'сухофрукты или ягоды, вода, сахар'],

            'Блинчики с мясом' => ['description' => 'Домашние блины с сытной мясной начинкой.', 'ingredients' => 'блины, мясной фарш, лук, специи, сметана'],
            'Блинчики с творогом' => ['description' => 'Нежные блинчики с творожной начинкой.', 'ingredients' => 'блины, творог, сахар, сметана'],
            'Блинчики со сметаной' => ['description' => 'Свежие блинчики, подаются со сметаной.', 'ingredients' => 'блины, сметана'],
            'Блинчики со сгущенкой' => ['description' => 'Сладкие блинчики со сгущенным молоком.', 'ingredients' => 'блины, сгущенное молоко'],
            'Хлеб белый' => ['description' => 'Пшеничный хлеб к первым и вторым блюдам.', 'ingredients' => 'мука пшеничная, вода, дрожжи, соль'],
            'Хлеб черный' => ['description' => 'Ржаной хлеб с насыщенным вкусом.', 'ingredients' => 'мука ржаная, вода, дрожжи, соль'],
            'Лаваш' => ['description' => 'Тонкий хлеб для подачи к горячим блюдам.', 'ingredients' => 'мука, вода, соль'],
        ];

        $imageMap = [
            'Борщ' => '/images/menu/borch.png',
            'Харчо' => '/images/menu/harcho.png',
            'Суп грибной' => '/images/menu/gribnoy.png',
            'Суп гороховый' => '/images/menu/gorohovyi.png',
            'Солянка' => '/images/menu/solyanka.png',
            'Лагман' => '/images/menu/lagman.png',
            'Шурпа' => '/images/menu/shurpa.png',
            'Хашлама' => '/images/menu/hashlama.png',
            'Суп с фрикадельками' => '/images/menu/frikadelki.png',
            'Суп рыбный' => '/images/menu/rybnyi.png',
            'Лапша домашняя' => '/images/menu/kurinyi.png',
            'Винегрет' => '/images/menu/vinegret.png',
            'Оливье' => '/images/menu/olivie.png',
            'Туборг' => '/images/menu/tuborg.png',
            'Сельдь под шубой' => '/images/menu/seldpodshuboy.png',
            'Салат из свежих огурцов и помидоров' => '/images/menu/ogurchipomidory.png',
            'Салат из крабовых палочек' => '/images/menu/krabovyi.png',
            'Морковь по-корейски' => '/images/menu/morkovpokoreiski.png',
            'Салат из капусты' => '/images/menu/svezhayakapusta.png',
            'Яйцо под майонезом' => '/images/menu/yaichopodmayonezom.png',
            'Закуска "Русская"' => '/images/menu/zakuskarusskayapng.png',
            'Сельдь с луком' => '/images/menu/seldslukom.png',
            'Свекла с чесноком' => '/images/menu/sveklaschesnokom.png',
            'Греческий' => '/images/menu/grecheskiy.png',
            'Цезарь' => '/images/menu/cezar.png',
            'Огурцы соленые' => '/images/menu/ogurcisolonie.png',
            'Мясо отбивное (свинина)' => '/images/menu/svinayaotbivnaya.png',
            'Мясо по-французски' => '/images/menu/myasopofrancuzski.png',
            'Мясо оригинальное' => '/images/menu/myasopooriginalnomu.png',
            'Свинина "под шубой"' => '/images/menu/svininapodshuboy.png',
            'Мясо с ананасами' => '/images/menu/myasosananasami.png',
            'Мясо по-барски' => '/images/menu/myasopobarski.png',
            'Жаркое по-домашнему в горшочке' => '/images/menu/zharkoevgorshochke.png',
            'Шашлык' => '/images/menu/shashlik.png',
            'Ребра тушеные' => '/images/menu/rebratusnenie.png',
            'Котлеты домашние' => '/images/menu/kotletydomashnie.png',
            'Голубцы' => '/images/menu/golubci.png',
            'Плов' => '/images/menu/plov.png',
            'Поджарка (свинина)' => '/images/menu/podzharka.png',
            'Печень' => '/images/menu/pechen.png',
            'Сосиски' => '/images/menu/sosiski.png',
            'Отбивная куриная' => '/images/menu/kurinayaotbivnaya.png',
            'Отбивная куриная с грибами' => '/images/menu/kurinayasgribami.png',
            'Котлета по-киевски' => '/images/menu/kotletapokievski.png',
            'Окорочка' => '/images/menu/okorochok.png',
            'Котлета куриная' => '/images/menu/kotletakurinaya.png',
            'Бифштекс с яйцом' => '/images/menu/bifshteks.png',
            'Говядина отварная' => '/images/menu/varenayagovyadina.png',
            'Мясо по-ирански' => '/images/menu/myasopoiranski.png',
            'Гуляш (говядина)' => '/images/menu/gulyash.png',
            'Горячая сковорода' => '/images/menu/goryachayaskovoroda.png',
            'Антрекот' => '/images/menu/antrekot.png',
            'Отбивная говяжья' => '/images/menu/otbivnayagovyadina.png',
            'Семга по-царски' => '/images/menu/semgapocarski.png',
            'Рыба жареная (минтай)' => '/images/menu/ribazharenaya.png',
            'Стейк' => '/images/menu/steik.png',
            'Пельмени' => '/images/menu/pelmeni.png',
            'Яичница с колбасой' => '/images/menu/yaitcnicaskolbasoy.png',
            'Макароны' => '/images/menu/makaroni.png',
            'Рис' => '/images/menu/ris.png',
            'Гречка' => '/images/menu/grechka.png',
            'Картофельное пюре' => '/images/menu/kartofelnoepure.png',
            'Сметана' => '/images/menu/smetana.png',
            'Кофе (с сахаром)' => '/images/menu/kofe.png',
            'Кофе двойной (с сахаром)' => '/images/menu/kofe.png',
            'Кофе со сливками 3в1' => '/images/menu/kofe3v1.png',
            'Чай зелёный (с сахаром)' => '/images/menu/zeleniychai.png',
            'Чай черный (с сахаром)' => '/images/menu/cherniychai.png',
            'Чай с лимоном (с сахаром)' => '/images/menu/chaislimonompng.png',
            'Компот' => '/images/menu/kompot.png',
            'Блинчики с мясом' => '/images/menu/blinchikismyasom.png',
            'Блинчики с творогом' => '/images/menu/blinchikistvorogom.png',
            'Блинчики со сметаной' => '/images/menu/blinchikisosmetanoy.png',
            'Блинчики со сгущенкой' => '/images/menu/blinchikisosguszhonkoy.png',
            'Хлеб белый' => '/images/menu/baton.jpg',
            'Хлеб черный' => '/images/menu/hleb.jpg',
            'Лаваш' => '/images/menu/lavash.jpg',
            
        ];

        foreach ($menuItems as $item) {
            if (isset($detailsMap[$item['name']])) {
                $item = array_merge($item, $detailsMap[$item['name']]);
            }

            $item['image_url'] = $imageMap[$item['name']] ?? null;
            MenuItem::create($item);
        }
    }
}
